name: Publish 
on:
    push:
        branches:
            - main

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Sync to Gitee 💕
              uses: wearerequired/git-mirror-action@master
              env:
                  SSH_PRIVATE_KEY: ${{ secrets.SSHKEY }}
              with:
                  source-repo: "git@github.com:CollapseNav/Collapsenav.Net.Tool.git"
                  destination-repo: "git@gitee.com:CollapseNav/test-push.git"
